name: myapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: 4.1.1
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  # google_maps_flutter: ^2.2.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  like_button: ^2.0.5
  # share_plus: ^6.3.0
  # maps_curved_line: ^1.0.2
  syncfusion_flutter_calendar: ^20.3.56
  url_launcher: ^6.1.7
  # syncfusion_flutter_maps: ^20.3.59
 

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
